### ISSUE TITLE
initial ssr request metrics

### ISSUE THREAD

**Issue by Enalmada** [godaddy/next-rum#3]
I don't see any output for initial ssr request, only links clicked after.  That may be obvious and unavoidable as I am new to react and next but wanted to confirm.

**Comment by 3rd-Eden** [comment]
That's correct, it's currently only tracking and reporting on navigation. The reason for this is that the traditional navigation e.g. first page load/hard refresh can be tracked (and usually is) by other analytic tools that are already present and loaded on the page. So it didn't make a lot of sense to duplicate that functionality.

However, if you feel strongly about having this functionality, I'll be more than happy to merge any PR's.
